spring:
  application:
    name: eureka-server #在注册的时候，配置文件中的spring.application.name
server:
  port: 7003
eureka:
  instance:
    hostname: peer3
  client:
    register-with-eureka: true #表示是否将自己注册到 Eureka Server，默认为 true。
    fetch-registry: true #表示是否从 Eureka Server 获取注册信息，默认为 true。
    service-url:
      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/ #设置与 Eureka Server 交互的地址，查询服务和注册服务都需要依赖这个地址，多个用，分隔